# Generated by Django 3.0.2 on 2021-04-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESOURCES_SERVER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
